#pragma once
#include "GL\glew.h"
namespace RA_FRAMEWORK
{
	static const unsigned DEPTH_QALIF_LUT_GL[7] = 
	{ GL_LESS, GL_EQUAL, GL_LEQUAL, GL_GREATER, GL_GEQUAL,GL_ALWAYS, GL_NEVER };

	static const unsigned TEX_FILTER_LUT_GL[5] =
	{ GL_NEAREST, GL_LINEAR, GL_NEAREST_MIPMAP_NEAREST, GL_LINEAR_MIPMAP_NEAREST, GL_LINEAR_MIPMAP_LINEAR};

	static const unsigned TEX_ADDRESS_MODE_LUT_GL[5] =
	{ GL_REPEAT, GL_MIRRORED_REPEAT, GL_CLAMP, GL_CLAMP_TO_BORDER, GL_MIRROR_CLAMP_TO_EDGE };

	static const unsigned TEX_FORMAT_LUT_GL[7] =
	{ GL_UNSIGNED_BYTE, GL_BYTE, GL_UNSIGNED_SHORT, GL_SHORT, GL_UNSIGNED_INT,	GL_INT,	GL_FLOAT };

}